import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { NavItem } from "./components/navbar/Navbar.types";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const navItems: NavItem[] = [
  { label: "Inicio", href: "/" },
  { label: "Teléfonos", href: "/category/telefonos" },
  { label: "Consolas", href: "/category/consolas" },
];
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
     
      >
        <Navbar items={navItems} />
        
        {children}
      </body>
    </html>
  );
}
